# Generated by Django 3.2.25 on 2024-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='huidige_club',
            new_name='actuele_club',
        ),
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='created_date',
            new_name='datum_invoer',
        ),
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='author',
            new_name='naam_auteur',
        ),
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='voetballer',
            new_name='naam_voetballer',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='published_date',
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='datum_laatste_aanpassing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
